name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: read

    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

      - name: Install Playwright Browsers
        run: |
          npx playwright install --with-deps
          npx playwright --version
          npx playwright show-config || true

      - name: Debug project structure
        run: |
          ls -R

      - name: Run Playwright tests
        run: npx playwright test --reporter=allure-playwright
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          STANDARD_USER: ${{ secrets.STANDARD_USER }}
          STANDARD_PASS: ${{ secrets.STANDARD_PASS }}
          LOCKED_USER: ${{ secrets.LOCKED_USER }}
          LOCKED_PASS: ${{ secrets.LOCKED_PASS }}

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ matrix.browser }}
          path: allure-results